install.packages("mniw")
install.packages("LaplacesDemon") # dmatrixnorm(")
install.packages("matrixsampling") # rinvwishart(")
install.packages("matrixcalc") # is.positive.definite(")
install.packages("invgamma") # rinvgamma
install.packages("matrixStats") # logSumExp(")
install.packages("loo")
# install.packages("microbenchmark")
install.packages("Rcpp")
install.packages("here")
install.packages("tidyverse")
install.packages("spreadr")
install.packages("ggraph")
install.packages("igraph")
install.packages("gifski")
install.packages("MLmetrics")
install.packages("png")
install.packages("grid")
install.packages("gridExtra")
install.packages("lhs")
install.packages("LICORS")
install.packages("latex2exp")
