# library(MNIW)
# library(fst)
library(mniw)
library(LaplacesDemon) # dmatrixnorm()
library(matrixsampling) # rinvwishart()
library(matrixcalc) # is.positive.definite()
library(invgamma) # rinvgamma
library(matrixStats) # logSumExp()
library(loo)
# library(microbenchmark)
library(Rcpp)
library(here)
library(tidyverse)
options(tidyverse.quiet = TRUE)
# library(matrixNormal) # dmatnorm() may have underflow
source("../R/func_gen_data.R")
source("../R/func_MNIW_sampler.R")
source("../R/func_FF.R")
source("../R/func_BS.R")
source("../R/func_FFBS.R")
source("../R/func_generate_grid_Dan.R")
sourceCpp("../src/FF.cpp")
sourceCpp("../src/BS.cpp")
sourceCpp("../src/rmn.cpp")